---
- name: Secrets Management — Install SOPS (Secrets on PGP / KMS)
  hosts: all
  become: true
  vars:
    sops_version: "3.8.1"
  tasks:
    - name: Download SOPS deb package
      ansible.builtin.get_url:
        url: "https://github.com/getsops/sops/releases/download/v{{ sops_version }}/sops_{{ sops_version }}_amd64.deb"
        dest: /tmp/sops.deb
        mode: '0644'

    - name: Install SOPS deb package
      ansible.builtin.apt:
        deb: /tmp/sops.deb
        state: present
...