---
- name: Infrastructure — DNS Nameserver configuration
  hosts: all
  become: true
  tasks:
    - name: Configure resolve.conf DNS nameservers
      ansible.builtin.copy:
        content: |
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        dest: /etc/resolv.conf
        mode: '0644'
...