---
- name: Restart NTP
  ansible.builtin.service:
    name: ntp
    state: restarted
  when: ansible_os_family == "Debian"

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted
  when: ansible_os_family == "Debian"
