[web]
web1 ansible_host=192.168.64.10 custom_port=8080
web2 ansible_host=192.168.64.11 custom_port=8081

[db]
db1 ansible_host=192.168.64.20

[staging]
web1
db1

[production]
web2

[servers:children]
web
db
