---
- name: Update apt cache if Debian-based
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Set system timezone
  community.general.timezone:
    name: "{{ common_system_timezone }}"
  notify: Restart cron

- name: Configure NTP servers
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: '0644'
  notify: Restart NTP
  when: ansible_os_family == "Debian"
